name: Release CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_test:
    name: Build and test xs2a-client-adapter (openjdk 1.11)
    runs-on: ubuntu-latest
    steps:
      - name: Clone xs2a-client-adapter repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build xs2a-client-adapter
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -V -q

      - name: Run Unit Tests
        run: mvn clean test -B -V -q

  deploy:
    name: Release to maven central
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Clone xs2a-client-adapter repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build xs2a-client-adapter and create jar files
        run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -V -q

      - name: Publish to Maven Central
        env:
          GPG_EXECUTABLE: gpg
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          gpg --version
          gpg --list-keys
          gpg --list-secret
          export GPG_TTY="$( tty )" #need to run to sign artifacts with maven
          echo "$GPG_SECRET_KEY" | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes || true
          echo "$GPG_OWNERTRUST" | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes || true
          mvn -ntp --settings maven_release_settings.xml \
          -Dhttp.keepAlive=false \
          -Dmaven.wagon.http.pool=false \
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
          -Prelease -DskipTests -U deploy